# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('original', models.CharField(blank=True, max_length=128)),
                ('source', models.ImageField(upload_to='source')),
                ('iso', models.CharField(blank=True, default='', max_length=128)),
                ('camera', models.CharField(blank=True, default='', max_length=128)),
                ('lens', models.CharField(blank=True, default='', max_length=128)),
                ('focal_length', models.CharField(blank=True, default='', max_length=128)),
                ('exposure_time', models.CharField(blank=True, default='', max_length=128)),
                ('date_taken', models.CharField(blank=True, default='', max_length=128)),
                ('aperture', models.CharField(blank=True, default='', max_length=128)),
                ('categories', models.ManyToManyField(blank=True, related_name='photos', to='photos.Category')),
            ],
        ),
    ]
