# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='original'),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='original'),
        ),
    ]
