# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170410_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploadDate',
        ),
    ]
