# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170323_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ImageField(upload_to='original'),
        ),
    ]
