# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20170412_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'sub-categories'},
        ),
    ]
