# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20170323_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='exposure_time',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
