# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20170323_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(blank=True, to='photos.Tag'),
        ),
    ]
