# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20170323_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='original',
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.ImageField(blank=True, upload_to='source'),
        ),
    ]
