# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20170412_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
