# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20170323_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.ImageField(upload_to='source'),
        ),
    ]
