# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20170324_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='original_filename',
        ),
    ]
