# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_remove_photo_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
