# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20170326_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
