# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20170417_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='takenDate',
            new_name='date_taken',
        ),
    ]
