# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20170326_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='filename',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
